//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace EntsoeCollectorService.EntsoeApi.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0", IsNullable=false)]
    public partial class GL_MarketDocument {
        
        private string mRIDField;
        
        private string revisionNumberField;
        
        private string typeField;
        
        private string processprocessTypeField;
        
        private PartyID_String sender_MarketParticipantmRIDField;
        
        private string sender_MarketParticipantmarketRoletypeField;
        
        private PartyID_String receiver_MarketParticipantmRIDField;
        
        private string receiver_MarketParticipantmarketRoletypeField;
        
        private System.DateTime createdDateTimeField;
        
        private ESMP_DateTimeInterval time_PeriodtimeIntervalField;
        
        private TimeSeries[] timeSeriesField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public string revisionNumber {
            get {
                return this.revisionNumberField;
            }
            set {
                this.revisionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("process.processType")]
        public string processprocessType {
            get {
                return this.processprocessTypeField;
            }
            set {
                this.processprocessTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender_MarketParticipant.mRID")]
        public PartyID_String sender_MarketParticipantmRID {
            get {
                return this.sender_MarketParticipantmRIDField;
            }
            set {
                this.sender_MarketParticipantmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender_MarketParticipant.marketRole.type")]
        public string sender_MarketParticipantmarketRoletype {
            get {
                return this.sender_MarketParticipantmarketRoletypeField;
            }
            set {
                this.sender_MarketParticipantmarketRoletypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receiver_MarketParticipant.mRID")]
        public PartyID_String receiver_MarketParticipantmRID {
            get {
                return this.receiver_MarketParticipantmRIDField;
            }
            set {
                this.receiver_MarketParticipantmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receiver_MarketParticipant.marketRole.type")]
        public string receiver_MarketParticipantmarketRoletype {
            get {
                return this.receiver_MarketParticipantmarketRoletypeField;
            }
            set {
                this.receiver_MarketParticipantmarketRoletypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createdDateTime {
            get {
                return this.createdDateTimeField;
            }
            set {
                this.createdDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("time_Period.timeInterval")]
        public ESMP_DateTimeInterval time_PeriodtimeInterval {
            get {
                return this.time_PeriodtimeIntervalField;
            }
            set {
                this.time_PeriodtimeIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeSeries")]
        public TimeSeries[] TimeSeries {
            get {
                return this.timeSeriesField;
            }
            set {
                this.timeSeriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class PartyID_String {
        
        private string codingSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingScheme {
            get {
                return this.codingSchemeField;
            }
            set {
                this.codingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class Point {
        
        private string positionField;
        
        private decimal quantityField;
        
        private decimal secondaryQuantityField;
        
        private bool secondaryQuantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public decimal quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal secondaryQuantity {
            get {
                return this.secondaryQuantityField;
            }
            set {
                this.secondaryQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondaryQuantitySpecified {
            get {
                return this.secondaryQuantityFieldSpecified;
            }
            set {
                this.secondaryQuantityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class Series_Period {
        
        private ESMP_DateTimeInterval timeIntervalField;
        
        private string resolutionField;
        
        private Point[] pointField;
        
        /// <remarks/>
        public ESMP_DateTimeInterval timeInterval {
            get {
                return this.timeIntervalField;
            }
            set {
                this.timeIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public Point[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class ESMP_DateTimeInterval {
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class ESMP_ActivePower {
        
        private UnitSymbol unitField;
        
        private float valueField;
        
        public ESMP_ActivePower() {
            this.unitField = UnitSymbol.MAW;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public enum UnitSymbol {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        deg,
        
        /// <remarks/>
        degC,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        g,
        
        /// <remarks/>
        h,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        Hz,
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        KVT,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        m2,
        
        /// <remarks/>
        m3,
        
        /// <remarks/>
        MAW,
        
        /// <remarks/>
        min,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        ohm,
        
        /// <remarks/>
        Pa,
        
        /// <remarks/>
        rad,
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VAh,
        
        /// <remarks/>
        VAr,
        
        /// <remarks/>
        VArh,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        Wh,
        
        /// <remarks/>
        WTT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class MktGeneratingUnit {
        
        private ResourceID_String mRIDField;
        
        private string nameField;
        
        private ESMP_ActivePower nominalPField;
        
        /// <remarks/>
        public ResourceID_String mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ESMP_ActivePower nominalP {
            get {
                return this.nominalPField;
            }
            set {
                this.nominalPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class ResourceID_String {
        
        private string codingSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingScheme {
            get {
                return this.codingSchemeField;
            }
            set {
                this.codingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class ESMP_Voltage {
        
        private UnitSymbol unitField;
        
        private float valueField;
        
        public ESMP_Voltage() {
            this.unitField = UnitSymbol.KVT;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class MktPSRType {
        
        private string psrTypeField;
        
        private ESMP_Voltage voltage_PowerSystemResourceshighVoltageLimitField;
        
        private MktGeneratingUnit[] powerSystemResourcesField;
        
        /// <remarks/>
        public string psrType {
            get {
                return this.psrTypeField;
            }
            set {
                this.psrTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voltage_PowerSystemResources.highVoltageLimit")]
        public ESMP_Voltage voltage_PowerSystemResourceshighVoltageLimit {
            get {
                return this.voltage_PowerSystemResourceshighVoltageLimitField;
            }
            set {
                this.voltage_PowerSystemResourceshighVoltageLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PowerSystemResources")]
        public MktGeneratingUnit[] PowerSystemResources {
            get {
                return this.powerSystemResourcesField;
            }
            set {
                this.powerSystemResourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class AreaID_String {
        
        private string codingSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingScheme {
            get {
                return this.codingSchemeField;
            }
            set {
                this.codingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0")]
    public partial class TimeSeries {
        
        private string mRIDField;
        
        private string businessTypeField;
        
        private string objectAggregationField;
        
        private AreaID_String inBiddingZone_DomainmRIDField;
        
        private AreaID_String outBiddingZone_DomainmRIDField;
        
        private ResourceID_String registeredResourcemRIDField;
        
        private string registeredResourcenameField;
        
        private string quantity_Measure_UnitnameField;
        
        private string curveTypeField;
        
        private string cancelledTSField;
        
        private MktPSRType mktPSRTypeField;
        
        private Series_Period[] periodField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public string businessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
            }
        }
        
        /// <remarks/>
        public string objectAggregation {
            get {
                return this.objectAggregationField;
            }
            set {
                this.objectAggregationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inBiddingZone_Domain.mRID")]
        public AreaID_String inBiddingZone_DomainmRID {
            get {
                return this.inBiddingZone_DomainmRIDField;
            }
            set {
                this.inBiddingZone_DomainmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outBiddingZone_Domain.mRID")]
        public AreaID_String outBiddingZone_DomainmRID {
            get {
                return this.outBiddingZone_DomainmRIDField;
            }
            set {
                this.outBiddingZone_DomainmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("registeredResource.mRID")]
        public ResourceID_String registeredResourcemRID {
            get {
                return this.registeredResourcemRIDField;
            }
            set {
                this.registeredResourcemRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("registeredResource.name")]
        public string registeredResourcename {
            get {
                return this.registeredResourcenameField;
            }
            set {
                this.registeredResourcenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("quantity_Measure_Unit.name")]
        public string quantity_Measure_Unitname {
            get {
                return this.quantity_Measure_UnitnameField;
            }
            set {
                this.quantity_Measure_UnitnameField = value;
            }
        }
        
        /// <remarks/>
        public string curveType {
            get {
                return this.curveTypeField;
            }
            set {
                this.curveTypeField = value;
            }
        }
        
        /// <remarks/>
        public string cancelledTS {
            get {
                return this.cancelledTSField;
            }
            set {
                this.cancelledTSField = value;
            }
        }
        
        /// <remarks/>
        public MktPSRType MktPSRType {
            get {
                return this.mktPSRTypeField;
            }
            set {
                this.mktPSRTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Period")]
        public Series_Period[] Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
}
